
name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: oscarlevin/pretext-full
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: setup git config
        run: |
          git config --global --add safe.directory $(pwd)
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: pip install -r requirements.txt --break-system-packages --no-cache-dir
      
      - name: Build with custom styling
        run: chmod +x build.sh && ./build.sh
      
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'output/web'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
